# Generated by Django 4.0.2 on 2022-02-11 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API_SignIn_Up', '0003_alter_userdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
