# Generated by Django 4.0.2 on 2022-02-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_SignIn_Up', '0001_initial'),
        ('API', '0002_remainderdata_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderdata',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_SignIn_Up.userdata'),
        ),
    ]
