# Generated by Django 4.0.2 on 2022-02-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_remainderdata_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderdata',
            name='added_by',
        ),
    ]
