# Generated by Django 4.0.2 on 2022-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_remainderdata_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderdata',
            name='photoName',
            field=models.FileField(upload_to=''),
        ),
    ]
