# Generated by Django 4.0.2 on 2022-02-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_remainderdata_photoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderdata',
            name='photoName',
        ),
    ]
