# Generated by Django 4.0.2 on 2022-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_remainderdata_photoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderdata',
            name='user_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
