# Generated by Django 4.0.2 on 2022-02-13 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remainderdata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderdata',
            name='user_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
